version: '3'

services:
  shopapotheke:
    build: ./src
    command: |
      bash -c 'while !</dev/tcp/redis/6379; do sleep 1; done; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080'
    volumes:
      - ./src/:/usr/src/app/
    ports:
    - "8083:8080"
    depends_on:
      - redis


  redis:
    image: redis:alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - 'redis_data:/data'


volumes:
  redis_data:
    driver: local